resources:
#- frontend/
- backend/
#- database/
#- ingress/



images:
- name: optum-azure-capstone-express-server
  newName: capstonenrwcregistry.azurecr.io/optum-azure-capstone-express-server
  newTag: latest
- name: optum-azure-capstone-flask-api
  newName: capstonenrwcregistry.azurecr.io/optum-azure-capstone-flask-api
  newTag: latest
- name: sqlite-db
  newName: capstonenrwcregistry.azurecr.io/sqlite-db
  newTag: latest
- name: optum-azure-capstone-angular-app
  newName: capstonenrwcregistry.azurecr.io/optum-azure-capstone-angular-app
  newTag: latest

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default